begin;
select set_config('test.admin',gen_random_uuid()::text,true),set_config('test.owner',gen_random_uuid()::text,true),set_config('test.other',gen_random_uuid()::text,true),set_config('test.supervisor',gen_random_uuid()::text,true),set_config('test.seller',gen_random_uuid()::text,true),set_config('test.new',gen_random_uuid()::text,true);
insert into auth.users(id) values(current_setting('test.admin')::uuid),(current_setting('test.owner')::uuid),(current_setting('test.other')::uuid),(current_setting('test.supervisor')::uuid),(current_setting('test.seller')::uuid),(current_setting('test.new')::uuid);
insert into public.gespro_profiles(user_id,username) select current_setting('test.'||v)::uuid,'test-'||left(current_setting('test.'||v),20) from unnest(array['admin','owner','other','supervisor','seller']) v;
insert into public.gespro_platform_admins values(current_setting('test.admin')::uuid);
select set_config('test.bank',(public.gespro_manage_access(current_setting('test.admin')::uuid,'create_bank','{"name":"Access test A"}') ->> 'id'),true);
select set_config('test.bank2',(public.gespro_manage_access(current_setting('test.admin')::uuid,'create_bank','{"name":"Access test B"}') ->> 'id'),true);
insert into public.gespro_memberships(bank_id,user_id,role) values(current_setting('test.bank')::uuid,current_setting('test.owner')::uuid,'owner'),(current_setting('test.bank2')::uuid,current_setting('test.other')::uuid,'owner'),(current_setting('test.bank')::uuid,current_setting('test.supervisor')::uuid,'supervisor'),(current_setting('test.bank')::uuid,current_setting('test.seller')::uuid,'seller');
select set_config('test.pos',(public.gespro_manage_access(current_setting('test.owner')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank'),'name','Assigned test')) ->> 'id'),true);
select set_config('test.pos2',(public.gespro_manage_access(current_setting('test.owner')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank'),'name','Unassigned test')) ->> 'id'),true);
select set_config('test.foreignpos',(public.gespro_manage_access(current_setting('test.other')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank2'),'name','Foreign test')) ->> 'id'),true);
insert into public.gespro_pos_assignments values(current_setting('test.bank')::uuid,current_setting('test.pos')::uuid,current_setting('test.supervisor')::uuid),(current_setting('test.bank')::uuid,current_setting('test.pos')::uuid,current_setting('test.seller')::uuid);
do $$ begin
 begin perform public.gespro_manage_access(current_setting('test.seller')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank'),'name','Forbidden'));raise exception 'seller write unexpectedly allowed';exception when insufficient_privilege then null;end;
 begin perform public.gespro_manage_access(current_setting('test.supervisor')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank'),'name','Forbidden'));raise exception 'supervisor write unexpectedly allowed';exception when insufficient_privilege then null;end;
 begin perform public.gespro_manage_access(current_setting('test.owner')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank2'),'name','Forbidden'));raise exception 'cross-bank write unexpectedly allowed';exception when insufficient_privilege then null;end;
 begin perform public.gespro_manage_access(current_setting('test.owner')::uuid,'check_member',jsonb_build_object('bank_id',current_setting('test.bank'),'role','owner'));raise exception 'owner escalation unexpectedly allowed';exception when insufficient_privilege then null;end;
 begin perform public.gespro_manage_access(current_setting('test.owner')::uuid,'check_member',jsonb_build_object('bank_id',current_setting('test.bank'),'role','seller','pos_ids',jsonb_build_array(current_setting('test.foreignpos'))));raise exception 'foreign assignment unexpectedly allowed';exception when raise_exception then if sqlerrm<>'Invalid point of sale' then raise;end if;end;
end $$;
select public.gespro_manage_access(current_setting('test.owner')::uuid,'create_member',jsonb_build_object('bank_id',current_setting('test.bank'),'role','seller','pos_ids',jsonb_build_array(current_setting('test.pos')),'user_id',current_setting('test.new'),'username','test-'||left(current_setting('test.new'),20),'display_name','New test seller'));
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
do $$ begin
 if (select count(*) from public.gespro_banks)<>1 then raise exception 'owner bank scope';end if;
 if exists(select 1 from public.gespro_profiles where user_id=current_setting('test.other')::uuid) then raise exception 'foreign profile exposed';end if;
 if (select count(*) from public.gespro_points_of_sale)<>2 then raise exception 'owner point scope';end if;
 if has_function_privilege(current_user,'public.gespro_manage_access(uuid,text,jsonb)','EXECUTE') then raise exception 'client privileged RPC exposed';end if;
 if has_table_privilege(current_user,'public.gespro_memberships','UPDATE') then raise exception 'client direct role write';end if;
end $$;
select set_config('request.jwt.claim.sub',current_setting('test.seller'),true);
do $$ begin if (select count(*) from public.gespro_points_of_sale)<>1 then raise exception 'seller assignment scope';end if;if (select count(*) from public.gespro_access_audit)<>0 then raise exception 'seller audit exposure';end if;end $$;
select set_config('request.jwt.claim.sub',current_setting('test.supervisor'),true);
do $$ begin if (select count(*) from public.gespro_points_of_sale)<>1 then raise exception 'supervisor assignment scope';end if;end $$;
reset role;
select public.gespro_manage_access(current_setting('test.owner')::uuid,'update_member',jsonb_build_object('bank_id',current_setting('test.bank'),'role','seller','pos_ids',jsonb_build_array(current_setting('test.pos')),'user_id',current_setting('test.seller'),'active',false));
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.seller'),true);
do $$ begin if (select count(*) from public.gespro_points_of_sale)<>0 or (select count(*) from public.gespro_banks)<>0 then raise exception 'suspended member retained access';end if;end $$;
reset role;
update public.gespro_profiles set active=false where user_id=current_setting('test.owner')::uuid;
do $$ begin begin perform public.gespro_manage_access(current_setting('test.owner')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank'),'name','Forbidden'));raise exception 'disabled profile allowed';exception when insufficient_privilege then null;end;end $$;
set local role anon;
do $$ begin if has_function_privilege(current_user,'public.gespro_manage_access(uuid,text,jsonb)','EXECUTE') or has_table_privilege(current_user,'public.gespro_access_audit','SELECT') then raise exception 'anonymous access';end if;end $$;
reset role;
select 'PASS: role isolation, no self-escalation, bank boundaries, assignments, suspension, audited writes and anonymous denial' as result;
rollback;
