begin;
select set_config('test.admin',gen_random_uuid()::text,true),set_config('test.owner',gen_random_uuid()::text,true),set_config('test.other',gen_random_uuid()::text,true),set_config('test.supervisor',gen_random_uuid()::text,true),set_config('test.seller',gen_random_uuid()::text,true),set_config('test.new',gen_random_uuid()::text,true);
insert into auth.users(id) values(current_setting('test.admin')::uuid),(current_setting('test.owner')::uuid),(current_setting('test.other')::uuid),(current_setting('test.supervisor')::uuid),(current_setting('test.seller')::uuid),(current_setting('test.new')::uuid);
insert into public.gespro_profiles(user_id,username) select current_setting('test.'||v)::uuid,'test-'||left(current_setting('test.'||v),20) from unnest(array['admin','owner','other','supervisor','seller']) v;
insert into public.gespro_platform_admins values(current_setting('test.admin')::uuid);
select set_config('test.bank',(public.gespro_manage_access(current_setting('test.admin')::uuid,'create_bank','{"name":"Access test A"}') ->> 'id'),true);
select set_config('test.bank2',(public.gespro_manage_access(current_setting('test.admin')::uuid,'create_bank','{"name":"Access test B"}') ->> 'id'),true);
insert into public.gespro_memberships(bank_id,user_id,role) values(current_setting('test.bank')::uuid,current_setting('test.owner')::uuid,'owner'),(current_setting('test.bank2')::uuid,current_setting('test.other')::uuid,'owner'),(current_setting('test.bank')::uuid,current_setting('test.supervisor')::uuid,'supervisor'),(current_setting('test.bank')::uuid,current_setting('test.seller')::uuid,'seller');
select set_config('test.pos',(public.gespro_manage_access(current_setting('test.owner')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank'),'name','Assigned test')) ->> 'id'),true);
select set_config('test.pos2',(public.gespro_manage_access(current_setting('test.owner')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank'),'name','Unassigned test')) ->> 'id'),true);
select set_config('test.foreignpos',(public.gespro_manage_access(current_setting('test.other')::uuid,'create_pos',jsonb_build_object('bank_id',current_setting('test.bank2'),'name','Foreign test')) ->> 'id'),true);
insert into public.gespro_pos_assignments values(current_setting('test.bank')::uuid,current_setting('test.pos')::uuid,current_setting('test.supervisor')::uuid),(current_setting('test.bank')::uuid,current_setting('test.pos')::uuid,current_setting('test.seller')::uuid);
select set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
insert into public.gespro_bank_configuration(bank_id,configuration) values(current_setting('test.bank')::uuid,jsonb_build_object('items',jsonb_build_array(jsonb_build_object('id','fl','name','FLORIDA AM','bank',null)),'removed','{}'::jsonb,'rates','{}'::jsonb,'closingTimes',jsonb_build_object('["fl","Access test A","closing"]',jsonb_build_object('time','23:59','zone','America/New_York')),'limits',jsonb_build_array(jsonb_build_object('lottery','fl','bank','Access test A','scope','bank','game','Directo','number','','days','["5.00","5.00","5.00","5.00","5.00","5.00","5.00"]'::jsonb))));
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.admin'),true);
select public.gespro_update_bank_entity(current_setting('test.bank')::uuid,current_setting('test.bank')::uuid,'bank','Renamed bank',true);
do $$ begin
 if not exists(select 1 from public.gespro_bank_configuration where bank_id=current_setting('test.bank')::uuid and configuration->'closingTimes' ? '["fl","Renamed bank","closing"]') then raise exception 'configuration keys not renamed';end if;
end $$;
select set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
select public.gespro_update_bank_entity(current_setting('test.bank')::uuid,current_setting('test.pos')::uuid,'pos','Renamed POS',false);
do $$ begin
 begin perform public.gespro_update_bank_entity(current_setting('test.bank2')::uuid,current_setting('test.foreignpos')::uuid,'pos','Forbidden',true);raise exception 'foreign mutation';exception when insufficient_privilege then null;end;
 begin perform public.gespro_update_bank_entity(current_setting('test.bank')::uuid,current_setting('test.bank')::uuid,'bank','Forbidden',true);raise exception 'owner bank mutation';exception when insufficient_privilege then null;end;
end $$;
select set_config('request.jwt.claim.sub',current_setting('test.seller'),true);
do $$ begin begin perform public.gespro_create_test_ticket(current_setting('test.pos')::uuid,gen_random_uuid(),'[]');raise exception 'suspended POS sold';exception when insufficient_privilege then null;end;end $$;
select set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
select public.gespro_update_bank_entity(current_setting('test.bank')::uuid,current_setting('test.pos')::uuid,'pos','Renamed POS',true);
select set_config('request.jwt.claim.sub',current_setting('test.seller'),true);
select public.gespro_create_test_ticket(current_setting('test.pos')::uuid,gen_random_uuid(),'[{"lottery":"FLORIDA AM","type":"DIRECTO","number":"01","amount":1}]');
reset role;
select 'PASS: rename keeps configuration, owner POS management, bank-only super rights, foreign bank denied, suspended POS blocked, reactivated POS works' as result;
rollback;
