package lol.gespro.pos;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.widget.*;import android.view.*;import android.print.*;import android.util.Base64;import java.io.*;
public class MainActivity extends Activity {
 WebView web;TextView banner;SunmiReceiptPrinter sunmi;PrintJob printJob;static final String HOME="https://gespro.lol/";
 boolean trusted(String u){Uri x=Uri.parse(u==null?"":u);return "https".equals(x.getScheme())&&"gespro.lol".equals(x.getHost())&&(x.getPort()==-1||x.getPort()==443);}
 @Override public void onCreate(Bundle b){super.onCreate(b);sunmi=new SunmiReceiptPrinter(this);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(0xff081d39);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i.consumeSystemWindowInsets();});banner=new TextView(this);banner.setText("GesPro • Ap chaje…");banner.setTextColor(-1);banner.setPadding(24,20,24,20);root.addView(banner);web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setUserAgentString(s.getUserAgentString()+" GesProAndroid/1.1");CookieManager.getInstance().setAcceptThirdPartyCookies(web,false);web.setWebViewClient(new WebViewClient(){
 @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(r.isForMainFrame()&&trusted(v.getUrl())){if(u.equals("gespro-settings://printers")){try{startActivity(new Intent(android.provider.Settings.ACTION_PRINT_SETTINGS));}catch(Exception e){Toast.makeText(MainActivity.this,"Paramèt enprimant pa disponib.",Toast.LENGTH_LONG).show();}return true;}if(u.equals("gespro-print://ticket")){printTicket();return true;}if(u.startsWith("gespro-share://image?")){share(r.getUrl());return true;}}return !trusted(u);}
 @Override public void onPageFinished(WebView v,String u){if(trusted(u)){banner.setVisibility(View.GONE);v.evaluateJavascript("document.documentElement.classList.add('gespro-native');window.print=function(){location.href='gespro-print://ticket'}",null);}}
 @Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame()){banner.setText("GesPro • Koneksyon pa disponib. Peze isit pou eseye ankò.");banner.setVisibility(View.VISIBLE);}}
 });banner.setOnClickListener(v->web.loadUrl(HOME));web.loadUrl(HOME);}
 void share(Uri uri){try{String data=uri.getQueryParameter("data");if(data==null||data.length()>16000000)throw new IOException();byte[] bytes=Base64.decode(data,Base64.DEFAULT);File f=new File(getCacheDir(),"ticket.png");try(FileOutputStream o=new FileOutputStream(f)){o.write(bytes);}Uri u=Uri.parse("content://lol.gespro.pos.tickets/ticket.png");Intent i=new Intent(Intent.ACTION_SEND);i.setType("image/png");i.putExtra(Intent.EXTRA_STREAM,u);i.setClipData(ClipData.newRawUri("GesPro",u));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share • GesPro"));}catch(Exception e){Toast.makeText(this,"Pataj la pa disponib. Eseye ankò.",Toast.LENGTH_LONG).show();}}
 void printTicket(){
  if(sunmi.available())new AlertDialog.Builder(this).setTitle("Enprime tikè").setItems(new String[]{"SUNMI entegre — 58 mm","Lòt printer / PDF"},(dialog,which)->{if(which==0)printSunmi();else printSystem();}).setNegativeButton("Anile",null).show();
  else printSystem();
 }
 void printSunmi(){
  if(sunmi.busy())return;
  String script="(function(){var imgs=Array.from(document.querySelectorAll('.monitor-print .receipt-artwork'));if(!imgs.length)return '';var w=384,h=imgs.reduce(function(n,i){return n+Math.ceil(i.naturalHeight*w/i.naturalWidth)},0);if(!isFinite(h)||h<1||h>16000)return '';var c=document.createElement('canvas');c.width=w;c.height=h;var x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,w,h);var y=0;imgs.forEach(function(i){var z=Math.ceil(i.naturalHeight*w/i.naturalWidth);x.drawImage(i,0,y,w,z);y+=z});return c.toDataURL('image/png').split(',')[1]})()";
  web.evaluateJavascript(script,value->{try{
   Object decoded=new org.json.JSONTokener(value).nextValue();if(!(decoded instanceof String))throw new IOException();String data=(String)decoded;
   if(data.length()==0||data.length()>4000000)throw new IOException();byte[] bytes=Base64.decode(data,Base64.DEFAULT);
   android.graphics.Bitmap bitmap=android.graphics.BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(bitmap==null||bitmap.getWidth()!=384||bitmap.getHeight()>16000)throw new IOException();sunmi.print(bitmap);
  }catch(Exception e){Toast.makeText(this,"Tikè a pa pare oswa li twò long. Sèvi ak Lòt printer / PDF.",Toast.LENGTH_LONG).show();}});
 }
 void printSystem(){try{if(printJob!=null&&!printJob.isCompleted()&&!printJob.isCancelled()&&!printJob.isFailed()){Toast.makeText(this,"Verifye travay enpresyon ki deja ouvè a.",Toast.LENGTH_LONG).show();return;}PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);if(pm==null)throw new IllegalStateException();printJob=pm.print("GesPro",web.createPrintDocumentAdapter("GesPro"),new PrintAttributes.Builder().setColorMode(PrintAttributes.COLOR_MODE_MONOCHROME).build());}catch(Exception e){Toast.makeText(this,"Aktive sèvis enprimant POS la.",Toast.LENGTH_LONG).show();}}
 @Override protected void onDestroy(){if(sunmi!=null)sunmi.close();super.onDestroy();}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
}
