"use client";
import {useEffect,useState} from 'react';
import {LotteryManagement,initialLotteryState,type LotteryState} from '@/components/lottery-management';
import {addDominicanCatalog} from '@/lib/dominican-lotteries';
import type{AccessContext} from '@/lib/access-types';
import {LanguageProvider} from '@/components/language-settings';
import {Button} from '@/components/ui/button';
import {LayoutGrid} from 'lucide-react';
import type {PosLayout} from '@/components/desktop-model-previews';
import {LayoutPreview} from '@/components/layout-preview';
const layoutLabels:Record<PosLayout,string>={option1:'GesPro V1',option2:'GesPro V2',option3:'GesPro V3'};
export function BankConfiguration({bank,access,onDirty}:{bank:{id:string;name:string};access:AccessContext;onDirty:(dirty:boolean)=>void}){
 const [state,setState]=useState<LotteryState|null>(null),[version,setVersion]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setBusy(true);try{const r=await fetch('/api/gespro/bank-configuration?bank='+encodeURIComponent(bank.id),{cache:'no-store'});const data=await r.json() as {configuration:LotteryState|null;version:number;error?:string};if(!r.ok)throw Error(data.error);setState(data.configuration??addDominicanCatalog(initialLotteryState));setVersion(data.version);setDirty(false);onDirty(false);setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'Pa disponib.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[bank.id]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 async function save(){setBusy(true);try{const r=await fetch('/api/gespro/bank-configuration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bank:bank.id,version,configuration:state})});const data=await r.json() as {configuration:LotteryState|null;version:number;error?:string};if(!r.ok)throw Error(data.error);setVersion(data.version);setDirty(false);onDirty(false);setMessage('✓ SAVE fini — '+bank.name+' mete ajou sou sèvè a.')}catch(e){setMessage(e instanceof Error?e.message:'Anrejistreman pa konfime.')}finally{setBusy(false)}}
 const supervisors=access.memberships.filter(m=>m.bank_id===bank.id&&m.role==='supervisor'&&m.active).map(m=>({id:m.user_id,bank:bank.name,name:access.profiles.find(p=>p.user_id===m.user_id)?.display_name||access.profiles.find(p=>p.user_id===m.user_id)?.username||'Sipèvizè'}));
 const management={supervisors,points:access.points.filter(p=>p.bank_id===bank.id&&p.active).map(p=>({id:p.id,bank:bank.name,name:p.name,supervisorId:supervisors.find(s=>access.assignments.some(a=>a.bank_id===bank.id&&a.pos_id===p.id&&a.user_id===s.id))?.id??null}))};
 return <section className="panel access-panel"><h2>Lotri ak konfigirasyon — {bank.name}</h2><p className="access-mode">Konfigirasyon bank • Lotri, limit ak lè fèmti aplike sou tikè yo apre anrejistreman. Tarif yo konsève; kalkil pri ak peman otomatik poko aktive. Mete yon lè fèmti pou chak lotri ou vle vann.</p><div className="bank-config-save"><span>{dirty?'● Gen chanjman pou SAVE':`✓ SAVE · v${version}`}</span><Button disabled={busy||!state||!dirty} onClick={()=>void save()} className="admin-save-button">{busy?'AP SOVE…':'SAVE'}</Button><Button disabled={busy} variant="outline" onClick={()=>{if(!dirty||window.confirm('Rechaje ap efase chanjman ou poko anrejistre yo. Kontinye?'))void load()}}>Rechaje</Button></div>{message&&<p role="status">{message}</p>}{!state?<p>Ap chaje konfigirasyon…</p>:<><div className="bank-config-layout"><label><LayoutGrid size={18}/><span>Modèl ekran pou vandè</span><select value={state.posLayout??'option1'} onChange={e=>{setState({...state,posLayout:e.target.value as PosLayout});setDirty(true);onDirty(true)}}><option value="option1">GesPro V1</option><option value="option2">GesPro V2</option><option value="option3">GesPro V3</option></select></label><p className="access-mode">Chwazi ki fason vandè yo wè ekran vant la. Chwazi a aplike lè yon vandè ouvri ekran POS li.</p><LayoutPreview layout={state.posLayout??'option1'}/></div><fieldset disabled={busy}><LanguageProvider><LotteryManagement bank={bank.name} isSuper={false} management={management} state={state} onChange={next=>{setState(next);setDirty(true);onDirty(true)}}/></LanguageProvider></fieldset></>}</section>
}
